name: Run Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - '.editorconfig'
      - '.*ignore'
    branches:
      - main

  pull_request:

env:
  USE_CODECOV_SERVICE: yes

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run the tests with coverage
        run: bun run test -- --coverage --coverageReporters json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ success() && env.USE_CODECOV_SERVICE == 'yes' && github.ref_name == 'main' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
